### ISSUE TITLE
Radial Menu problem with action cam

### ISSUE THREAD

**Issue by Flauschedrache** [RaidcoreGG/GW2-RadialMenus#3]
Radial menu (mounts) does not seem to work with action cam. When action cam is active, moving the mouse moves the camera instead of unlocking the mouse to choose the mount, meaning you can't select a mouse while using action cam. Is it possible to somehow use the radial menu without manually disabling action camera first everytime?

**Comment by DeltaGW2** [comment]
You need to set the corresponding bind for Action Cam under Nexus' Options -> Game Keybinds.

It will automatically disable it allowing you to select an item, then re-enable it afterwards.
